version: '3.8'

networks:
  lumen:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: lumen-nginx
    ports:
      - "3070:5000"
    depends_on:
      - php
    networks:
      - lumen
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx

  postgres:
    image: postgres:14-alpine3.15
    container_name: lumen-postgres
    ports:
      - "5435:5435"
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      DB_DATABASE_TESTING: ${DB_DATABASE_TESTING}
    volumes:
      - ./docker/postgres/pg-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - lumen

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen-php
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DB_CONNECTION}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    volumes:
      - ./:/app
    networks:
      - lumen

  composer:
    image: composer:latest
    container_name: lumen-composer
    volumes:
      - .:/app
    depends_on:
      - php
    networks:
      - lumen
    command: install --ignore-platform-reqs --no-scripts


volumes:
  pg-data:
    driver: local
